[project]
name = "urfu-llm-documents"
version = "0.1.0"
description = "Зависимости проверки №24"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "pdf2image>=1.17.0",
    "pytesseract>=0.3.13",
]
